### PR TITLE
refactor math algos

### PR DESCRIPTION
**Pull request by omeganullptr**
may fix performance issues, may totally bork things.

looking for peer review before merging to master.

### CODE REVIEW

**Comment by calexil** [comment]
@reconman looks clear to me, please test. This is my buddy rytak, he moved all the maths to floats to accelerate the calculations, should increase prediction speed by a noticeable margin

**Comment by reconman** [comment]
https://www.w3schools.com/js/js_numbers.asp

> Unlike many other programming languages, JavaScript does not define different types of numbers, like integers, short, long, floating-point etc.
>
> JavaScript numbers are always stored as double precision floating point numbers, following the international IEEE 754 standard.
> 
> This format stores numbers in 64 bits, where the number (the fraction) is stored in bits 0 to 51, the exponent in bits 52 to 62, and the sign in bit 63

This PR has no effect.

If it does, please add timers to the code and compare both versions.

The operation to measure would be the calculation of a new chromosome based on an imported one.

There should be at least 10k imported battle records, so a few more (which are added during the calculation) aren't scientifically significant.

**Comment by omeganullptr** [comment]
That would explain a bit. Thanks for the link recon. 

Appears that my changes here make it compliant with JS arithmetic recommendations. Done via JIT division for floating numbers that require a decimal output. Thought process behind it is trimming the overhead generated by having to read non zero values in the later read bits when parsing for decimal placement.

**Comment by omeganullptr** [comment]
Closing PR. Slowdown appears to be happening elsewhere within the code. I'll make an issue post if anything is found.

**Pull request closed without merging**
