### PR TITLE
readme updates, fresh data

### PR DESCRIPTION
**Pull request by calexil**

### CODE REVIEW

**Comment by reconman** [comment]
I'll have to clean up your branch later today, it's showing me that you've added stuff that's already in the master branch.

**Comment by calexil** [comment]
I was trying to get caught up to your commits.. did I do it wrong?

**Comment by reconman** [comment]
You'd have to do some force pushing after rebasing or cherry-picking to get it correct, which are advanced git commands.

I'd rather do it myself because a lot can go wrong.

**Comment by calexil** [comment]
okay well I only made small edits anyways, just the readme, and a new batch of data.

Should I close this pr?

**Comment by reconman** [comment]
Leave it as it is, I'll deal with everything as soon as I get home.

**Comment by calexil** [comment]
thank you, and sorry if I made your life harder. We had a request for fresh data on the subreddit

**Review by reconman — APPROVED** [review]

**Pull request merged**
